version: '3.3'

services: 
    api1:
        build:
            context: .
            dockerfile: src/api1/Dockerfile
        restart: always
        ports: 
            - "9090:80"
        networks: 
            - softplandotnet
    api2:
        depends_on: 
            - api1
        build: 
            context: .
            dockerfile: src/api2/Dockerfile
        ports: 
            - "9191:80"
        restart: always
        env_file: 
            - ./config/api2.env
        networks: 
            - softplandotnet
networks: 
    softplandotnet: